import { NextRequest, NextResponse } from "next/server";
import { YoutubeTranscript } from "youtube-transcript";
import { extractVideoId } from "@/lib/youtube";

export const runtime = "nodejs";

function formatTimestamp(ms: number): string {
  const totalSeconds = Math.floor(ms / 1000);
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;
  const pad = (n: number) => n.toString().padStart(2, "0");
  return hours > 0
    ? `${hours}:${pad(minutes)}:${pad(seconds)}`
    : `${minutes}:${pad(seconds)}`;
}

function decodeHtmlEntities(text: string): string {
  return text
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">");
}

export async function POST(req: NextRequest) {
  let body: { url?: string; lang?: string };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid request body." }, { status: 400 });
  }

  const rawInput = body.url?.trim();
  if (!rawInput) {
    return NextResponse.json(
      { error: "Please provide a YouTube video URL." },
      { status: 400 }
    );
  }

  const videoId = extractVideoId(rawInput);
  if (!videoId) {
    return NextResponse.json(
      {
        error:
          "That doesn't look like a valid YouTube link. Try a full URL like https://www.youtube.com/watch?v=... or a youtu.be link.",
      },
      { status: 400 }
    );
  }

  try {
    const rawSegments = await YoutubeTranscript.fetchTranscript(videoId, {
      lang: body.lang,
    });

    const segments = rawSegments.map((s) => ({
      start: s.offset,
      duration: s.duration,
      timestamp: formatTimestamp(s.offset),
      text: decodeHtmlEntities(s.text),
    }));

    const fullText = segments.map((s) => s.text).join(" ");

    return NextResponse.json({
      videoId,
      segments,
      fullText,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    const isDisabled = /disabled|not available|no transcript/i.test(message);
    return NextResponse.json(
      {
        error: isDisabled
          ? "This video doesn't have captions available (transcripts must be enabled by the video owner or auto-generated by YouTube)."
          : `Could not fetch transcript: ${message}`,
      },
      { status: 502 }
    );
  }
}
